# Generated by Django 5.2.12 on 2026-04-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_inn", models.TextField(primary_key=True, serialize=False)),
                ("customer_name", models.TextField()),
                ("customer_region", models.TextField()),
            ],
            options={
                "db_table": "customer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AppUser",
            fields=[
                ("customer_inn", models.TextField(primary_key=True, serialize=False)),
                ("password_hash", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "app_user",
            },
        ),
    ]
