# Generated by Django 5.2.12 on 2026-04-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SteSearchSource",
            fields=[
                ("ste_id", models.TextField(primary_key=True, serialize=False)),
                ("ste_name", models.TextField()),
                ("ste_category", models.TextField()),
                ("ste_attributes", models.TextField()),
            ],
            options={
                "db_table": "ste_data",
                "managed": False,
            },
        ),
    ]
