# Generated by Django 5.2.12 on 2026-04-05 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSteDayPenalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ste_id", models.CharField(db_index=True, max_length=128)),
                ("day", models.DateField(db_index=True)),
                ("mult", models.FloatField(default=0.75)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ste_day_penalties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "ste_id", "day"),
                        name="events_user_ste_day_pen_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSteRelevanceModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ste_id", models.CharField(db_index=True, max_length=128)),
                (
                    "quick_leave_penalty_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "bonus_product_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("bonus_product_until", models.DateTimeField(blank=True, null=True)),
                (
                    "bonus_search_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("bonus_search_until", models.DateTimeField(blank=True, null=True)),
                ("shield_until", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ste_relevance_modifiers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "ste_id"], name="events_user_user_id_b15956_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "ste_id"), name="events_user_ste_rel_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserTelemetryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=64)),
                ("event_id", models.CharField(max_length=64, unique=True)),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                (
                    "ste_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "search_query_id",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("event_at", models.DateTimeField(db_index=True)),
                ("dwell_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("active_time_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-event_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-event_at"],
                        name="events_user_user_id_b34f89_idx",
                    ),
                    models.Index(
                        fields=["user", "ste_id"], name="events_user_user_id_734bc2_idx"
                    ),
                ],
            },
        ),
    ]
